apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
data:
# 'sa' em base64 é: c2E=
  sqlserver-user: c2E= 
  # 'SuaSenhaForte123!' em base64 U3VhU2VuaGFGb3J0ZTEyMyE=
  sqlserver-password: U3VhU2VuaGFGb3J0ZTEyMyE=